CREATE TABLE IF NOT EXISTS `Level` (
  `level_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `level` TEXT NOT NULL)

CREATE TABLE IF NOT EXISTS `DDAnswer` (
  `dd_answer_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `dd_question_id` INTEGER NOT NULL,
  `dd_answer` TEXT NOT NULL,
  `is_correct` INTEGER NOT NULL,
  FOREIGN KEY(`dd_question_id`) REFERENCES `DDQuestion`(`dd_question_id`)
  ON UPDATE NO ACTION ON DELETE CASCADE )

CREATE TABLE IF NOT EXISTS `DDQuestion` (
  `dd_question_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `level_id` INTEGER NOT NULL,
  `dd_question` TEXT NOT NULL,
  FOREIGN KEY(`level_id`) REFERENCES `Level`(`level_id`)
  ON UPDATE NO ACTION ON DELETE CASCADE )

CREATE TABLE IF NOT EXISTS `FBAnswer` (
  `fb_answer_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `fb_question_id` INTEGER NOT NULL,
  `fb_answer` TEXT NOT NULL,
  `is_correct` INTEGER NOT NULL,
  FOREIGN KEY(`fb_question_id`) REFERENCES `FBQuestion`(`fb_question_id`)
  ON UPDATE NO ACTION ON DELETE CASCADE )

CREATE TABLE IF NOT EXISTS `FBQuestion` (
  `fb_question_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `level_id` INTEGER NOT NULL,
  FOREIGN KEY(`level_id`) REFERENCES `Level`(`level_id`)
  ON UPDATE NO ACTION ON DELETE CASCADE )

CREATE TABLE IF NOT EXISTS `HLAnswer` (
  `hl_answer_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `hl_question_id` INTEGER NOT NULL,
  `hl_answer` TEXT NOT NULL, `type` TEXT,
  FOREIGN KEY(`hl_question_id`) REFERENCES `HLQuestion`(`hl_question_id`)
  ON UPDATE NO ACTION ON DELETE CASCADE )

CREATE TABLE IF NOT EXISTS `HLQuestion` (
  `hl_question_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `level_id` INTEGER NOT NULL,
  `hl_question` TEXT NOT NULL,
  FOREIGN KEY(`level_id`) REFERENCES `Level`(`level_id`)
  ON UPDATE NO ACTION ON DELETE CASCADE )

CREATE TABLE IF NOT EXISTS `MultipleChoiceA` (
  `mc_answer_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `mc_question_id` INTEGER NOT NULL,
  `mc_answer` TEXT NOT NULL,
  `is_correct` INTEGER NOT NULL,
  FOREIGN KEY(`mc_question_id`) REFERENCES `MultipleChoiceQ`(`mc_question_id`)
  ON UPDATE NO ACTION ON DELETE CASCADE )

CREATE TABLE IF NOT EXISTS `MultipleChoiceQ` (
  `mc_question_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `level_id` INTEGER NOT NULL,
  `mc_question` TEXT NOT NULL,
  FOREIGN KEY(`level_id`) REFERENCES `Level`(`level_id`)
  ON UPDATE NO ACTION ON DELETE CASCADE )",
